Manual CD

diff --git a/.github/workflows/CD.yaml b/.github/workflows/CD.yaml
--- a/.github/workflows/CD.yaml
+++ b/.github/workflows/CD.yaml
@@ -18,7 +18,7 @@ on:
 
 jobs:
   deploy:
-    runs-on: ubuntu-latest
+    runs-on: hf-cicd-ubuntu-latest
     environment: ${{ github.event.inputs.environment }}  # Configura el ambiente dinámicamente
 
     steps:
@@ -59,14 +59,21 @@ jobs:
           if [[ -z "${{ env.SERVICE }}" ]]; then
             echo "Error: SERVICE is empty. Deployment aborted."
             exit 1
-          elif [[ "${{ env.SERVICE }}" == "chat" ]]; then
-            #npm run deploy:chat -- --c "[B-389745] testing cicd" --skip-confirmation
-          elif [[ "${{ env.SERVICE }}" == "CCO MS" ]]; then
-            #npm run deploy:cco-ms -- --c "[B-389745] testing cicd" --skip-confirmation
-          elif [[ "${{ env.SERVICE }}" == "CCO PS" ]]; then
-            #npm run deploy:cco-ms -- --c "[B-389745] testing cicd" --skip-confirmation
           else
-            echo "Error: Unknown service '${{ env.SERVICE }}'. Deployment aborted."
-            exit 1
+            case "${{ env.SERVICE }}" in
+              "chat")
+                npm run deploy:chat -- --c "[B-389745] testing cicd" --skip-confirmation
+                ;;
+              "CCO MS")
+                npm run deploy:cco-ms -- --c "[B-389745] testing cicd" --skip-confirmation
+                ;;
+              "CCO PS")
+                npm run deploy:cco-ms -- --c "[B-389745] testing cicd" --skip-confirmation
+                ;;
+              *)
+                echo "Error: Unknown service '${{ env.SERVICE }}'. Deployment aborted."
+                exit 1
+                ;;
+            esac
           fi
         working-directory: my-project
